name: JTEconomy

version: 1.0.0
api: 5.0.0

src-namespace-prefix: te
main: te\Economy

author: JustTimmm
website: https://github.com/JustTimmm

permissions:
    money.command.player:
        default: true
    money.command.player.see:
        default: true